Added settings to Video section
PrudinnikDmitriy/Add-settings-to-Video-section pull request #1
Opened 2022-10-24 11:42 UTC by PrudinnikDmitriy

2022-10-24 14:53 UTC, AndriiHrohodza requested changes

2022-10-24 14:53 UTC, AndriiHrohodza commented on src/sections/home-video.liquid
> +                      <h2
use condtion pls

2022-10-24 14:53 UTC, AndriiHrohodza commented on src/sections/home-video.liquid
> +                      <div class="mb-4" {{ block.shopify_attributes }}>{{ block.settings.subheading }}</div>
use condtion pls

2022-10-31 12:26 UTC, PrudinnikDmitriy commented on src/sections/home-video.liquid
> +                      <h2
@AndriiHrohodza  fixed

2022-10-31 12:51 UTC, yevheniitsuryk approved these changes

2022-10-31 13:59 UTC, AndriiHrohodza approved these changes

2022-10-31 16:11 UTC, merged